version: '3'

services:
  voibi-agenda:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass the variables during build time
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    image: voibi-agenda:latest
    container_name: voibi-agenda
    ports:
      - "3000:3000"
    restart: always
    environment:
      - PORT=3000
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - CRON_SECRET=${CRON_SECRET}
